[build-system]
requires = [
  "setuptools >= 80; python_version >= '3.9'",
  "setuptools >= 75; python_version  == '3.8'",
  "setuptools >= 44; python_version < '3.8' and python_version >= '2.7'",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "systemd-dbus"
version = "0.3"
description = """Thin Python bindings for a minimal set of systemd service management commands, using sd-bus. Also includes functionality for creating unit files, as well as polkit rules."""
requires-python = ">=2.7"
license = "Apache-2.0"
license-files = ["LICENSE", "LICENSES/LICENSE.LGPL2.1"]
authors = [{ name = "Jeffrey Smith", email = "jeffrey.smith@acceldata.io" }]
maintainers = [{ name = "Jeffrey Smith", email = "jeffrey.smith@acceldata.io" }]
readme = "README.md"
classifiers = ["Operating System :: POSIX :: Linux"]

[project.optional-dependencies]
dev = [
  "pytest >= 9.0, < 10; python_version >= '3.9'",
  "pytest >= 6.0, < 7; python_version >= '3.6' and python_version < '3.9'",
  "pytest==4.6.11; python_version == '2.7'",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
filterwarnings = ["ignore::UserWarning:systemd_dbus"]
# This is the default, in case someone is somewhere where DBus is not available.
# To run all of the tests, run `pytest -m ""`
addopts = "-m not-integration"
markers = [
  "integration: requires D-Bus and systemd (deselect with '-m not integration')",
]
